# Stage 1: Build Image
FROM node:18-alpine AS builder

WORKDIR /app

# Ensure we have package files
COPY package.json package-lock.json ./
RUN npm ci

# Copy source
COPY . .

# Build vite app to /dist
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy build artifacts
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
